<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.Data.HashFunction.Core" />
    <PackageReference Include="System.Data.HashFunction.Interfaces" />
    <PackageReference Include="System.Data.HashFunction.xxHash" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FastRsync\FastRsync.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="FastRsyncLegacy231">
      <HintPath>TestData\FastRsyncLegacy231.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="TestData\FastRsyncLegacy231.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
